Document: webapps
Title: Debian webapps Manual
Author: <insert document author here>
Abstract: This manual describes what webapps is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webapps/webapps.sgml.gz

Format: postscript
Files: /usr/share/doc/webapps/webapps.ps.gz

Format: text
Files: /usr/share/doc/webapps/webapps.text.gz

Format: HTML
Index: /usr/share/doc/webapps/html/index.html
Files: /usr/share/doc/webapps/html/*.html
